[package]
name = "jocky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecheck = "0.6.9"
futures-lite = "1.12.0"
serde_json = "1"
parking_lot = "0.12.1"
itertools = "0.10.5"
flume = "0.10.14"

# Debugging
anyhow = "1"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
cap = "0.1.1"
humantime = "2.1.0"
humansize = "2.1.2"
mimalloc = "0.1.32"
memmap2 = "0.5.8"

puppet = { version = "0.4.0", default-features = false }
tokio = { version = "1", features = ["full"] }
rkyv = { version = "0.7.39", features = ["validation"] }
tantivy = { git = "https://github.com/ChillFish8/tantivy.git", branch = "main", features = ["quickwit"] }

[target.'cfg(target_os = "linux")'.dependencies]
glommio = "0.7.0"

[features]
disable-aio = []
