[package]
name = "jocky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
puppet = "0.2.0"
memmap2 = "0.5.8"
bytecheck = "0.6.9"
futures-lite = "1.12.0"
bytes = "1.3.0"
serde_json = "1"
parking_lot = "0.12.1"
itertools = "0.10.5"

# Debugging
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

tokio = { version = "1", features = ["full"] }
datacake-crdt = { version = "0.3.0", features = ["rkyv-support"] }
rkyv = { version = "0.7.39", features = ["validation"] }
tantivy = { git = "https://github.com/quickwit-oss/tantivy.git", branch = "commit-changes" }
